sudo: required
services:
  - docker
  - node

before_install:
  - docker build -t ashishjava113/docker-react .

script:
  - docker run -e CI=true ashishjava113/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerapp"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-893995758721"
  bucket_path: "dockerapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
